import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'ru' | 'tm';

interface LanguageContextProps {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, section?: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// Словарь переводов для всего сайта
const translations: Record<Language, Record<string, Record<string, string>>> = {
  ru: {
    navbar: {
      catalog: 'Каталог',
      auto: 'Автотовары',
      clothing: 'Одежда',
      home: 'Дом и уют',
      accessories: 'Аксессуары',
      tracking: 'Отслеживание',
      admin: 'Админка',
      cart: 'Корзина',
      all_clothing: 'Вся одежда',
      men: 'Мужская',
      women: 'Женская',
    },
    hero: {
      tagline_all: 'Премиальные товары на заказ',
      tagline_auto: 'Автомобильные аксессуары премиум-класса',
      tagline_clothing: 'Одежда и обувь на заказ',
      tagline_home: 'Изысканный домашний текстиль и декор',
      desc_all: 'Прямая премиальная доставка лучших фабричных товаров из Китая в Ашхабад прямыми авиарейсами и быстрыми автодорожными коридорами.',
      desc_auto: 'Индивидуальные кожаные 3D-коврики, технологичные держатели и благородные арома-диффузоры. Превратите салон своего автомобиля в безукоризненное пространство комфорта.',
      desc_clothing: 'Безупречный крой, натуральные материалы высшей пробы. Кашемировые пальто, теплые мериносовые джемперы, футболки из плотного хлопка и итальянская обувь ручной работы.',
      desc_home: 'Создайте атмосферу тепла и утонченности с элитным постельным бельем из тенселя, дизайнерскими свечами на соевом воске и лаконичной керамикой ручной работы.',
      air_shipping: 'Авиа заказ • 150 TMT / КГ',
      air_desc: 'Прямые авиарейсы в Ашхабад. Скорость и надежность доставки за 7-10 дней.',
      road_shipping: 'Сухопутный заказ • 50 TMT / КГ',
      road_desc: 'Экономичная транспортировка крупных заказов сушей. Время доставки составляет 25-30 дней.',
      scroll_down: 'Листайте вниз для просмотра товаров',
      go_to_sections: 'Перейти к разделам',
      motto: '«Лучшее из Китая — теперь на новом уровне»',
    },
    catalog: {
      select_section: 'Выберите интересующий раздел',
      personal_showcase: 'Каждый раздел оформлен как персональная витрина',
      section_auto: 'Автотовары',
      section_auto_desc: 'Индивидуальные кожаные 3D-коврики, органайзеры Premium класса и элитные ароматизаторы.',
      section_clothing: 'Премиум Одежда',
      section_clothing_desc: 'Кашемировые пальто, теплые мериносовые джемперы, тяжелый трикотаж и обувь ручной работы.',
      section_clothing_men: 'Мужская одежда & обувь',
      section_clothing_men_desc: 'Кашемировые пальто, теплые мериносовые джемперы, тяжелый трикотаж и обувь ручной работы.',
      section_clothing_women: 'Женская одежда & обувь',
      section_clothing_women_desc: 'Шелковые платья, шерстяные блейзеры, трикотаж и изящная обувь.',
      section_home: 'Дом & Уют',
      section_home_desc: 'Элитное постельное белье из тенселя, интерьерный декор, диффузоры и свечи ручной работы.',
      section_accessories: 'Аксессуары',
      section_accessories_desc: 'Премиальные механические и кварцевые часы, ремни из натуральной кожи и утонченные украшения.',
      section_tracking: 'Отслеживание товара',
      section_tracking_desc: '«Где мой товар? / Harydym nirede?» — Моментально отслеживайте статус вашей доставки по коду заказа.',
      open_section: 'Открыть раздел',
      featured_new: 'Премиальные новинки сезона',
      featured_desc: 'Эксклюзивные новинки, доступные к заказу прямо сейчас',
      elimizdakiler: 'Товары в наличии',
      back_to_catalog: '← Назад в весь каталог',
      viewing_section: 'Вы просматриваете раздел:',
      search_placeholder: 'Поиск...',
      only_in_stock: 'Только в наличии',
      sort_label: 'Сорт:',
      sort_newest: 'Сначала новые',
      sort_price_asc: 'Меньшая цена',
      sort_price_desc: 'Большая цена',
      not_found: 'Ничего не найдено',
      not_found_desc: 'Попробуйте изменить поисковый запрос, выбрать другой раздел или показать товары, которых временно нет в наличии.',
      reset_filters: 'Сбросить фильтры',
      search_results: 'Найдено результатов:',
      premium_selection: 'LEVEL UP PREMIUM SELECTION • 2026',
      all_catalog: 'Весь каталог товаров',
      clothing_all: 'Вся одежда и обувь',
      clothing_men: 'Мужская коллекция одежды',
      clothing_women: 'Женская коллекция одежды',
      premium_section_sub: 'Раздел премиальной коллекции',
    },
    subcategories: {
      'коврики': 'Кожаные 3D-коврики',
      'органайзеры': 'Органайзеры и сумки в багажник',
      'держатели': 'Держатели и зарядные устройства',
      'ароматизаторы': 'Ароматизаторы и диффузоры',
      'куртки': 'Верхняя одежда и куртки',
      'футболки': 'Футболки, худи и свитшоты',
      'обувь': 'Мужская и женская обувь',
      'платья': 'Элегантные платья',
      'декор': 'Стильный декор и интерьерные свечи',
      'текстиль': 'Постельный текстиль из тенселя',
      'аксессуары': 'Практичные аксессуары и девайсы',
      'mats': 'Коврики в салон и в багажник',
      'car_cover': 'Чехол для машины',
      'seat_cover': 'Чехол для сидения',
      'armrest_mats': 'Коврики для подлокотники',
      'lights_glass_body': 'Стекла фара корпус',
      'others': 'Другие (пока)',
    },
    features: {
      feature1_title: 'Работа на заказ',
      feature1_desc: 'Любые размеры, цвета и комплектации изготавливаются индивидуально под ваши требования. Прямые поставки с лучших фабрик Китая без посредников.',
      feature2_title: 'Удобный выбор доставки',
      feature2_desc: 'Выберите оптимальный для себя тариф: скоростной Авиа заказ за 7-10 дней (150 TMT / кг) или экономичный Сухопутный заказ за 25-30 дней (50 TMT / кг).',
      feature3_title: 'Высокие стандарты LLU',
      feature3_desc: 'Мы гарантируем строжайший контроль качества каждой отправляемой позиции, бережную экспресс-упаковку и полное сопровождение сделки до ваших дверей.',
    },
    productCard: {
      out_of_stock: 'Нет в наличии',
      order_button: 'Заказать',
      delivery: 'Доставка:',
      air: 'Авиа заказ',
      truck: 'Сухопутный заказ',
      category_auto: 'Авто',
      category_home: 'Дом',
      category_men: 'Мужское',
      category_women: 'Женское',
    },
    productDetails: {
      choose_size: 'Выберите размер:',
      choose_size_error: 'Пожалуйста, выберите размер!',
      choose_option: 'Выберите вариант:',
      delivery_method: 'Способ доставки из Китая:',
      no_extra: 'Без доплаты',
      item_price: 'Цена товара:',
      weight_note_air: 'Доставка (✈️ Авиа): оплачивается при получении по весу.',
      weight_note_truck: 'Доставка (🚛 Авто): оплачивается при получении по весу.',
      add_to_cart: 'Добавить в корзину',
      added: 'Добавлено!',
      sold_out: 'Данный товар временно распродан',
      specs: 'Характеристики',
      sku: 'Артикул',
      brand: 'Бренд',
      material: 'Материал',
      weight: 'Вес товара',
      days: ' дней',
      category_auto: 'Автотовары',
      category_home: 'Дом и уют',
      category_clothing_men: 'Одежда / Мужское',
      category_clothing_women: 'Одежда / Женское',
      extra_fee: 'Без доплаты',
    },
    reviews: {
      title: 'Отзывы о товаре',
      tab_order: 'Заказать',
      tab_reviews: 'Отзывы',
      add_review: 'Оставить отзыв',
      write_review_desc: 'Поделитесь вашим мнением об этом товаре',
      your_name: 'Ваше имя',
      your_comment: 'Ваш отзыв',
      rating_label: 'Ваша оценка:',
      submit_review: 'Отправить отзыв',
      no_reviews: 'Отзывов пока нет. Будьте первым!',
      average_rating: 'Средняя оценка:',
      empty_fields_error: 'Пожалуйста, введите имя и текст отзыва, а также укажите оценку!',
      success_message: 'Спасибо! Ваш отзыв успешно добавлен.',
    },
    cart: {
      title: 'Ваша корзина',
      empty: 'Корзина пуста',
      empty_desc: 'Добавьте товары из каталога, чтобы оформить заказ',
      checkout_title: 'Оформление заказа',
      your_name: 'Ваше имя',
      phone_number: 'Номер телефона',
      delivery_address: 'Адрес доставки в Ашхабаде',
      comment: 'Комментарий к заказу (размер, цвет и др.)',
      total_payment: 'Итого к оплате:',
      delivery_note: 'Доставка оплачивается при получении по весу:',
      payment_method: 'Способ оплаты вашего заказа:',
      payment_desc: 'Наличными курьеру при получении товара, либо авансовым платежом на телефонный счёт на номер:',
      back: 'Назад',
      confirm_order: 'Подтвердить заказ',
      order_success: 'Заказ успешно оформлен!',
      order_success_desc: 'Спасибо за ваш заказ. Мы свяжемся с вами в ближайшее время для подтверждения деталей.',
      order_id: 'Номер заказа:',
      customer: 'Покупатель:',
      phone: 'Телефон:',
      payment_types: 'Способы Оплаты',
      on_delivery: 'При получении:',
      on_delivery_desc: 'наличными курьеру при доставке.',
      prepayment: 'Авансовый платёж:',
      prepayment_desc: 'пополнение телефонного счёта на номер телефона:',
      continue_shopping: 'Продолжить покупки',
      validation_name: 'Пожалуйста, введите ваше имя',
      validation_phone: 'Пожалуйста, введите номер телефона',
      validation_phone_start: 'Номер телефона должен начинаться с +993',
      validation_phone_digits: 'Формат номера: +993 64 30-01-86 (8 цифр после кода)',
      validation_address: 'Пожалуйста, укажите адрес доставки',
      submitting: 'Оформление...',
      cart_tab: 'Корзина',
      history_tab: 'История',
      favorites_tab: 'Избранное',
      favorites_empty: 'В избранном пока пусто',
      favorites_empty_desc: 'Отмечайте товары сердечком, чтобы сохранить их здесь',
      method_courier: 'Доставка по Ашхабаду',
      method_regions: 'Доставка по регионам (велаятам)',
    },
    footer: {
      desc: 'Премиальные коллекции одежды, автомобильного инвентаря и товаров для дома на заказ из Китая. Высокий уровень качества и надежности.',
      sections: 'Разделы каталога',
      contacts: 'Контакты и заказы',
      work_hours: 'Принимаем заказы 7/24',
      payment_info: 'Оплата и доставка',
      payment_desc: 'Оплата производится после получения товара через курьера.',
      rights: 'Все права защищены. Доставка из Китая на новом уровне.',
      privacy: 'Политика конфиденциальности',
      terms: 'Публичная оферта',
    },
    products: {
      // Переводы для изначальных продуктов
      'Кожаные 3D-коврики ручной работы Premium': 'Кожаные 3D-коврики ручной работы Premium',
      'Кожаный органайзер в багажник Premium': 'Кожаный органайзер в багажник Premium',
      'Магнитный держатель MagSafe с беспроводной зарядкой': 'Магнитный держатель MagSafe с беспроводной зарядкой',
      'Премиальный ароматизатор салона из авиационного сплава': 'Премиальный ароматизатор салона из авиационного сплава',
      'Зимняя куртка-парка премиум-класса': 'Зимняя куртка-парка премиум-класса',
      'Футболка из тяжелого хлопка Heavyweight 300g': 'Футболка из тяжелого хлопка Heavyweight 300g',
      'Кожаные лоферы ручной работы (Италия)': 'Кожаные лоферы ручной работы (Италия)',
      'Шелковое платье-комбинация миди': 'Шелковое платье-комбинация миди',
      'Дизайнерская соевая свечь в гипсе': 'Дизайнерская соевая свечь в гипсе',
      'Постельное белье из тенселя Premium': 'Постельное белье из тенселя Premium',
      'Мужские механические часы LLU Chrono Skeleton Premium': 'Мужские механические часы LLU Chrono Skeleton Premium',
      'Мужской кожаный ремень LLU Classic Gold': 'Мужской кожаный ремень LLU Classic Gold',
      'Женские кварцевые часы LLU Luxury Diamond': 'Женские кварцевые часы LLU Luxury Diamond',
      'Очки солнцезащитные LLU Black Cat-Eye': 'Очки солнцезащитные LLU Black Cat-Eye',
      // Описание продуктов
      'Индивидуальный пошив под вашу модель автомобиля...': 'Индивидуальный пошив под вашу модель автомобиля...',
    }
  },
  tm: {
    navbar: {
      catalog: 'Katalog',
      auto: 'Awtoulag harytlary',
      clothing: 'Eşikler',
      home: 'Öý we rahatlyk',
      accessories: 'Aksessuarlar',
      tracking: 'Yzarlamak',
      admin: 'Admin',
      cart: 'Sebet',
      all_clothing: 'Ähli eşikler',
      men: 'Erkek',
      women: 'Aýal',
    },
    hero: {
      tagline_all: 'Sargyt boýunça premium harytlar',
      tagline_auto: 'Premial awtoulag aksessuarlary',
      tagline_clothing: 'Sargyt boýunça eşikler we aýakgaplar',
      tagline_home: 'Öý üçin nepis dokma we bezegler',
      desc_all: 'Hytaýyň iň gowy zawod harytlaryny göni uçuşlar we çalt awtomobil ýollary arkaly Aşgabada göni premial eltip bermek.',
      desc_auto: 'Ýörite 3D deri aýaklyklar, tehnologiki saklaýjylar we yslar. Ulagyňyzyň salonyny kämil rahatlyk giňişligine öwrüň.',
      desc_clothing: 'Kämil kesim, ýokary hilli tebigy materiallar. Kaşemir palto, ýyly merinos džemperleri, galyň pagta futbolkalar we italýan el işi aýakgaplary.',
      desc_home: 'Tansel düşek daşlary, soýa şemleri we el işi keramika önümleri bilen öýüňizde ýylylyk we nepislik gurşawyny dörediň.',
      air_shipping: 'Avia sargyt • 150 TMT / KG',
      air_desc: 'Aşgabada göni uçuşlar. 7-10 günüň içinde çalt we ygtybarly eltip bermek.',
      road_shipping: 'Gara ýol sargyt • 50 TMT / KG',
      road_desc: 'Uly sargytlary gury ýer arkaly tygşytly eltip bermek. Eltip berme wagty 25-30 gün.',
      scroll_down: 'Harytlary görmek üçin aşak süýşüriň',
      go_to_sections: 'Bölümlere geçmek',
      motto: '«Hytaýdan iň gowusy — indi täze derejede»',
    },
    catalog: {
      select_section: 'Gyzyklanýan bölümiňizi saýlaň',
      personal_showcase: 'Her bölüm ýörite witrina hökmünde bezeldi',
      section_auto: 'Awtoulaglar',
      section_auto_desc: 'Deri 3D aýaklyklar, Premium klas bagaj organaýzerleri we ajaýyp yslar.',
      section_clothing: 'Eşikler & Aýakgaplar',
      section_clothing_desc: 'Kaşemir palto, ýyly merinos džemperleri, galyň trikotaž we el işi aýakgaplar.',
      section_clothing_men: 'Erkek eşik & aýakgaplar',
      section_clothing_men_desc: 'Kaşemir palto, ýyly merinos džemperleri, galyň trikotaž we el işi aýakgaplar.',
      section_clothing_women: 'Aýal eşik & aýakgaplar',
      section_clothing_women_desc: 'Ýüpek köýnekler, ýüň bleyzerler, sumkalar we nepis aýakgaplar.',
      section_home: 'Öý & Rahatlyk',
      section_home_desc: 'Tansel düşek daşlary, öý bezegleri, diffuzorlar we el işi şemler.',
      section_accessories: 'Aksessuarlar',
      section_accessories_desc: 'Premial mehaniki we kwars sagatlar, arassa deriden kemerler we nepis bezegler.',
      section_tracking: 'Harydy yzarlamak',
      section_tracking_desc: '«Где мой товар? / Harydym nirede?» — Sargyt belgiňiz arkaly eltip berme ýagdaýyny çalt bilip bilersiňiz.',
      open_section: 'Bölümi açmak',
      featured_new: 'Möwsümiň premial täze harytlary',
      featured_desc: 'Häzirki wagtda sargyt edip boljak eksklýuziw täze harytlar',
      elimizdakiler: 'Elimizdakiler',
      back_to_catalog: '← Ähli kataloga dolanmak',
      viewing_section: 'Siz şu bölümi görýärsiňiz:',
      search_placeholder: 'Gozle...',
      only_in_stock: 'Diňe eldekiler',
      sort_label: 'Tertiple:',
      sort_newest: 'Ilki täzeler',
      sort_price_asc: 'Arzan bahadan',
      sort_price_desc: 'Gymmat bahadan',
      not_found: 'Hiç zat tapylmady',
      not_found_desc: 'Gözleg sözüni üýtgedip, başga bölümi saýlap ýa-da wagtlaýynça elde bolmadyk harytlary görkezip bilersiňiz.',
      reset_filters: 'Süzgüçleri arassalamak',
      search_results: 'Tapylan netijeler:',
      premium_selection: 'LEVEL UP PREMIUM SELECTION • 2026',
      all_catalog: 'Ähli harytlar katalogy',
      clothing_all: 'Ähli eşikler we aýakgaplar',
      clothing_men: 'Erkekleriň eşik ýygyndysy',
      clothing_women: 'Aýallaryň eşik ýygyndysy',
      premium_section_sub: 'Premial ýygyndynyň bölüми',
    },
    subcategories: {
      'коврики': '3D deri aýaklyklar',
      'органайзеры': 'Organaýzerler we goş torbalary',
      'держатели': 'Telefon saklaýjylar we zarýadnikler',
      'ароматизаторы': 'Yslar we diffuzorlar',
      'куртки': 'Penjekler we ýokarky eşikler',
      'футболки': 'Futbolkalar, hudiler we switşotlar',
      'обувь': 'Erkek we aýal aýakgaplary',
      'платья': 'Gözel köýnekler',
      'декор': 'Sözgiler we öý bezegleri',
      'текстиль': 'Tansel düşek toplumlary',
      'аксессуары': 'Peýdaly aksessuarlar we enjamlar',
      'mats': 'Salon we bagaj kowrikler',
      'car_cover': 'Awtoulag çeholy',
      'seat_cover': 'Sidenýa çeholy',
      'armrest_mats': 'Podlokotnik kowrikleri',
      'lights_glass_body': 'Faran otdelni aynasy sona menzesh owadanla',
      'others': 'Başgalar (häzirlikçe)',
    },
    features: {
      feature1_title: 'Sargyt boýunça iş',
      feature1_desc: 'Islendik ölçeg, reňk we komplektasiýa siziň talaplaryňyza görä ýörite taýýarlanylýar. Hytaýyň iň gowy zawodlaryndan araçysyz göni üpjünçilik.',
      feature2_title: 'Eltip bermegiň amatly saýlawy',
      feature2_desc: 'Özüňiz üçin iň amatly tarifi saýlaň: 7-10 günde çalt Avia sargyt (150 TMT / kg) ýa-da 25-30 günde tygşytly Gara ýol sargyt (50 TMT / kg).',
      feature3_title: 'LLU-nyň ýokary standartlary',
      feature3_desc: 'Biz ugradylýan her bir harydyň hiline berk gözegçilik edilmegini, seresaply ekspress-gaplamany we sargydyňyz gapyňyza gelýänçä doly goldawy kepillendirýäris.',
    },
    productCard: {
      out_of_stock: 'Elde ýok',
      order_button: 'Sargyt etmek',
      delivery: 'Eltip berme:',
      air: 'Avia sargyt',
      truck: 'Gara ýol sargyt',
      category_auto: 'Awtoulag',
      category_home: 'Öý',
      category_men: 'Erkek',
      category_women: 'Aýal',
    },
    productDetails: {
      choose_size: 'Ölçeg saýlaň:',
      choose_size_error: 'Haýyş, ölçeg saýlaň!',
      choose_option: 'Görnüşini saýlaň:',
      delivery_method: 'Hytaýdan eltip berme görnüşi:',
      no_extra: 'Goşmaça tölegsiz',
      item_price: 'Harydyň bahasy:',
      weight_note_air: 'Eltip berme (✈️ Awia): alanyňyzda agramyna görä tölenýär.',
      weight_note_truck: 'Eltip berme (🚛 Awtoulag): alanyňyzda agramyna görä tölenýär.',
      add_to_cart: 'Sebede goşmak',
      added: 'Goşuldy!',
      sold_out: 'Bu haryt wagtlaýynça gutardy',
      specs: 'Häsiýetnamalar',
      sku: 'Artikul',
      brand: 'Brend',
      material: 'Material',
      weight: 'Agramy',
      days: ' gün',
      category_auto: 'Awtoulag harytlary',
      category_home: 'Öý we rahatlyk',
      category_clothing_men: 'Eşikler / Erkek',
      category_clothing_women: 'Eşikler / Aýal',
      extra_fee: 'Goşmaça tölegsiz',
    },
    reviews: {
      title: 'Haryt barada seslenmeler',
      tab_order: 'Sargyt etmek',
      tab_reviews: 'Seslenmeler',
      add_review: 'Seslenme galdyr',
      write_review_desc: 'Bu haryt barada öz pikiriňizi paýlaşyň',
      your_name: 'Adyňyz',
      your_comment: 'Siziň seslenmeňiz',
      rating_label: 'Bahaňyz:',
      submit_review: 'Seslenmäni ibermek',
      no_reviews: 'Häzirki wagtda seslenmeler ýok. Ilkinji boluň!',
      average_rating: 'Ortaça baha:',
      empty_fields_error: 'Haýyş, adyňyzy, teswiriňizi ýazyň we bahaňyzy saýlaň!',
      success_message: 'Sag boluň! Siziň seslenmeňiz üstünlikli goşuldy.',
    },
    cart: {
      title: 'Siziň sebediňiz',
      empty: 'Sebet boş',
      empty_desc: 'Sargyt etmek üçin katalogdan haryt goşuň',
      checkout_title: 'Sargydy resmileşdirmek',
      your_name: 'Adyňyz',
      phone_number: 'Telefon belgiňiz',
      delivery_address: 'Aşgabatdaky salgyňyz',
      comment: 'Sargyt barada teswir (ölçeg, reňk we ş.m.)',
      total_payment: 'Jemi tölemeli:',
      delivery_note: 'Eltip berme agramyna görä alanyňyzda tölenýär:',
      payment_method: 'Sargydyňyzyň töleg görnüşi:',
      payment_desc: 'Harydy alanyňyzda kuryere nagt görnüşinde, ýa-da telefon belgisiniň hasabyna öňünden tölemek arkaly:',
      back: 'Yza',
      confirm_order: 'Sargydy tassyklamak',
      order_success: 'Sargyt üstünlikli ýerine ýetirildi!',
      order_success_desc: 'Sargydyňyz üçin sag boluň. Sargyt şertlerini tassyklamak üçin tiz wagtdan sizin bilen habarlaşarys.',
      order_id: 'Sargyt belgisi:',
      customer: 'Sargytçy:',
      phone: 'Telefon:',
      payment_types: 'Töleg Usullary',
      on_delivery: 'Alanyňyzda:',
      on_delivery_desc: 'eltip berlende kuryere nagt görnüşinde.',
      prepayment: 'Öňünden töleg:',
      prepayment_desc: 'telefon belgisiniň hasabyny doldurmak arkaly:',
      continue_shopping: 'Söwdany dowam etdir',
      validation_name: 'Haýyş, adyňyzy ýazyň',
      validation_phone: 'Haýyş, telefon belgiňizi ýazyň',
      validation_phone_start: 'Telefon belgisi +993 bilen başlamaly',
      validation_phone_digits: 'Format: +993 64 30-01-86 (koddan soň 8 sany san)',
      validation_address: 'Haýyş, eltip berme salgysyny ýazyň',
      submitting: 'Resmileşdirilýär...',
      cart_tab: 'Sebet',
      history_tab: 'Taryh',
      favorites_tab: 'Halanlarym',
      favorites_empty: 'Halan harytlaryňyz ýok',
      favorites_empty_desc: 'Harytlary bu ýere goşmak üçin ýürek şekiljigine basyň',
      method_courier: 'Aşgabada eltip bermek',
      method_regions: 'Welaýatlara eltip bermek',
    },
    footer: {
      desc: 'Hytaýdan sargyt boýunça ýokary hilli eşikleriň, awtoulag enjamlarynyň we öý harytlarynyň premial ýygyndysy. Ýokary derejede hil we ygtybarlylyk.',
      sections: 'Katalog bölümleri',
      contacts: 'Habarlaşmak we sargytlar',
      work_hours: 'Sargytlary 7/24 kabul edýäris',
      payment_info: 'Töleg we eltip bermek',
      payment_desc: 'Töleg haryt kuryer arkaly alnandan soň amala aşyrylýar.',
      rights: 'Ähli hukuklar goralan. Hytaýdan eltip bermek täze derejede.',
      privacy: 'Gizlinlik syýasaty',
      terms: 'Ylalaşyk şertleri',
    },
    products: {
      // Переводы для изначальных продуктов
      'Кожаные 3D-коврики ручной работы Premium': 'Premium el işi 3D deri aýaklyklar',
      'Кожаный органайзер в багажник Premium': 'Premium deri bagaj organaýzeri',
      'Магнитный держатель MagSafe с беспроводной зарядкой': 'MagSafe simsiz zarýadly magnit saklaýjy',
      'Премиальный ароматизатор салона из авиационного сплава': 'Awiasiýa gatyşykly gurnalan premial salon ysy',
      'Зимняя куртка-парка премиум-класса': 'Premial gyşky park penjege',
      'Футболка из тяжелого хлопка Heavyweight 300g': 'Heavyweight 300g galyň pagtaly futbolka',
      'Кожаные лоферы ручной работы (Италия)': 'Italýan el işi deri loferleri',
      'Шелковое платье-комбинация миди': 'Midi ýüpek köýnek',
      'Дизайнерская соевая свечь в гипсе': 'Gips gapdaky dizaýner soýa şemi',
      'Постельное белье из тенселя Premium': 'Premium tansel düşek daşy',
      'Мужские механические часы LLU Chrono Skeleton Premium': 'LLU Chrono Skeleton Premium erkek mehaniki sagady',
      'Мужской кожаный ремень LLU Classic Gold': 'LLU Classic Gold erkek deri kemeri',
      'Женские кварцевые часы LLU Luxury Diamond': 'LLU Luxury Diamond aýal kwars sagady',
      'Очки солнцезащитные LLU Black Cat-Eye': 'LLU Black Cat-Eye aýal gün äýnekleri',
      // Описание продуктов
      'Индивидуальный пошив под вашу модель автомобиля. Полная защита ворса, идеальная посадка и роскошный внешний вид вашей машины. Изготавливаются индивидуально.': 'Ulagyňyzyň modeline görä ýörite tikin. Tozana we çyglylyga garşy doly gorag, ajaýyp durnuklylyk we kämil daşky görnüş. Ýörite sargyt boýunça taýýarlanýar.',
      'Эргономичный кожаный органайзер для хранения вещей в багажнике. Износостойкий материал, прочная строчка и логотип бренда. Сохраняйте безукоризненный порядок.': 'Ýük goşlaryňyzy tertipli saklamak üçin ergonomiki deri organaýzer. Könelmege çydamly material we pugta tikinler. Bagajda kämil tertip dörediň.',
      'Премиальное крепление на дефлектор с сильными неодимовыми магнитами и технологией MagSafe. Быстрая беспроводная зарядка и идеальная фиксация на любой дороге.': 'Güýçli neodim magnitleri we MagSafe tehnologiýasy bolan premial telefon saklaýjy. Çalt simsiz zarýad beriş we islendik ýolda berk duruş.',
      'Изысканный диффузор в дефлектор. Корпус из матового авиационного алюминия, натуральные французские масла с благородным ароматом элитного парфюма.': 'Salon üçin ajaýyp ys diffuzory. Gözenekli awiasiýa alýumin gaby, nepis fransuz ýaglary we ajaýyp elit atyr ysy.',
      'Теплая удлиненная куртка-парка с водоотталкивающим мембранным покрытием и натуральным пуховым наполнителем. Защита от ветра и морозов с изысканным городским стилем.': 'Suw geçirmeýän membranaly örtügi we tebigy pamyk doldurgyjy bolan ýyly uzyn park penjege. Ýel we sowuk howadan ajaýyp şäher bezeginde gorag.',
      'Классический силуэт оверсайз из плотного 100% хлопка. Отлично держит форму, износостойкая ткань премиального качества, дышащая и мягкая к телу.': 'Galyň 100% pagtadan ýasalan nusgawy oversized biçüwdäki futbolka. Formasyny ajaýyp saklaýar, premial hilli matasy gaty ýumşak we amatlydyr.',
      'Стильные и комфортные лоферы из мягкой итальянской замши. Ручной шов, ортопедическая кожаная стелька и легкая гибкая подошва для безупречного стиля каждый день.': 'Ýumşak italýan derisinden ýasalan ajaýyp we amatly lofer aýakgaplary. El işi tikinler we her gün üçin ýeňil çeýe daban.',
      'Элегантное скользящее платье на тонких регулируемых бретелях. Изготовлено из 100% натурального шелка. Струящийся силуэт, подчеркивающий утонченность образа.': 'Inçe we sazlap bolýan bagjykly gözel köýnek. 100% tebigy ýüpekden taýýarlandy. Syzylyp duran keşp, siziň nepisligiňizi has-da görkezer.',
      'Стильная ароматическая свечь из натурального соевого воска в крафтовом кашпо из высокопрочного гипса. Аромат сандала и табака погрузит ваш дом в истинный покой.': 'Süňk gips gapda ýasalan tebigy soýa şemi. Sandal we temmäki ysy öýüňizi hakyky asuda gurşawa we rahatlyga beslär.',
      'Роскошный комплект постельного белья из 100% тенселя (эвкалиптовое волокно). Шелк на ощупь, гипоаллергенный, отлично дышит и дарит невероятный комфорт во сне.': '100% tansel (ewkalipt süýümi) ýasalan täsin uly düşek toplumy. Ýüpek ýumşaklygy, gipoallergen we ajaýyp dem alýan gurluş.',
    }
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const stored = localStorage.getItem('levelup_lang');
    return (stored === 'tm' || stored === 'ru') ? stored : 'ru';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('levelup_lang', newLang);
  };

  const t = (key: string, section?: string): string => {
    if (!section) {
      // Ищем везде
      const sections = Object.keys(translations[lang]);
      for (const sec of sections) {
        if (translations[lang][sec][key]) {
          return translations[lang][sec][key];
        }
      }
      return key;
    }

    const value = translations[lang][section]?.[key];
    if (value !== undefined) {
      return value;
    }

    // Если нет перевода, пробуем найти в дефолтном (русском)
    const fallbackValue = translations['ru'][section]?.[key];
    if (fallbackValue !== undefined) {
      return fallbackValue;
    }

    return key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
